### ISSUE TITLE
Show version aliasing when listing installed versions

### ISSUE THREAD

**Issue by OmriSama** [asdf-vm/asdf#1024]
### Is your feature request related to a problem? Please describe

When using `asdf list`, you get to see all the versions installed of each plugin installed. This also includes versions like `lts` for Node, which at the time of writing aliases to `14.17.5`. It's great that `asdf` has this, as `fnm` does too I believe.

### Describe the proposed solution

I would like to see alias versions like `lts` show what they currently alias to:

Instead of:

```zsh
➜  ~  asdf list nodejs
  14.17.2
  14.17.5
  lts
➜  ~
```

You'd have:

```zsh
➜  ~  asdf list nodejs
  14.17.2
  14.17.5
  lts -> 14.7.5
➜  ~
```

Or something of the like.

### Describe similar `asdf` features and why they are not sufficient

Not aware of any `asdf` features that explicitly make this alias clear.

### Describe other workarounds you've considered

No other workarounds considered.

**Comment by jthegedus** [comment]
Aliases are specific to each plugin, in this instance, `nodejs`. This is because aliasing is not something the core has ever considered, it is entirely implemented in the plugin. The core is unaware of any aliasing as it is an install-time feature. I am not sure this is possible without handing off the `list` responsibility to the plugin.

**Comment by OmriSama** [comment]
@jthegedus Is it possible to feature a sort of "adapter"/"interface" for plugin developers who wanted to implement alias display? Or would that be too far out of the scope of the project?

**Comment by jthegedus** [comment]
We could hand off `list` responsibility to plugins. Whether or not the benefit vs development effort is there is another question. Perhaps another solution is to capture symlinks in the `list` command :thinking: 

I do not like the idea of aliases as they are simply a shortcut, and only a shortcut for that single time they are used. `asdf install nodejs lts` changes over time and so the `lts` on your machine is no longer an LTS. Also, your `lts` may be different to my `lts. And reporting you are using `lts` when trying to resolve a bug only causes more problems. I personally would advise against using aliases. Unless I am misunderstanding their utility.

**Comment by Stratus3D** [comment]
For the record I agree with @jthegedus on aliases. I understand they are convenient but I believe they are at odds with asdf's goal of deterministic behavior.

**Comment by polarathene** [comment]
I mentioned this in more detail in https://github.com/asdf-vm/asdf-nodejs/issues/308 but it might be helpful to anyone landing here:

Get the version that `nodejs lts` currently points to:

```bash
readlink -f $(asdf where nodejs lts) | awk -F '/' '{print $(NF)}'
```

Set the `local` version to an explicit version instead of the `lts` alias:

```bash
asdf local nodejs "$(readlink -f $(asdf where nodejs lts) | awk -F '/' '{print $(NF)}')"
```

You may also prefer to be more explicit with the `lts` alias you install, and prefer the one associated to each major version which would be less ambiguous (_minor and patch versions would still vary over time of course_):

```bash
asdf install nodejs "$(asdf latest nodejs lts-)"
```

---

You could likewise use these approaches with `asdf current nodejs` to get the version or set it too:

```console
# Use `awk` to split the returned line by white-space and take the 2nd column:
$ asdf current nodejs | awk '{print $2}'

lts


# Resolve the `current` nodejs version:
$ readlink -f $(asdf where nodejs $(asdf current nodejs | awk '{print $2}' )) | awk -F '/' '{print $(NF)}'

16.17.0


# Set the explicitly resolved version locally:
$ asdf local nodejs $(readlink -f $(asdf where nodejs $(asdf current nodejs | awk '{print $2}' )) | awk -F '/' '{print $(NF)}')
```

Obviously those a bit long to remember / type, so create a shell alias for them if they're useful to you :sweat_smile:
