### ISSUE TITLE
We may have broken plugin test

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#1083]
@tsuyoshicho yeah it does look like we may have broken something here. @raxod502 would you be willing to take a look at @tsuyoshicho builds? Output shows things like:

```
asdf-awscli: Could not download https://github.com/aws/aws-cli/archive/--asdf-plugin-gitref.tar.gz
```

clearly `--asdf-plugin-gitref` was a flag for the tag, not the tag itself.

_Originally posted by @Stratus3D in https://github.com/asdf-vm/asdf/issues/1078#issuecomment-959141878_

**Comment by raxod502** [comment]
Let me take a look

**Comment by raxod502** [comment]
See https://github.com/asdf-vm/asdf/pull/1084

**Comment by Stratus3D** [comment]
@n-rodriguez also encountered this issue here - https://github.com/jbox-web/asdf-squarectl/actions/runs/1426185845

**Comment by itspngu** [comment]
The CI for the 3 asdf plugins I wrote broke down 3 days ago, all at the same time. Is that related to this issue? I did some superficial digging and couldn't figure out what's wrong.

- https://github.com/itspngu/asdf-cloudsql-proxy
- https://github.com/itspngu/asdf-mongo-tools
- https://github.com/itspngu/asdf-mongosh

I'll be watching this issue because I lack the time to familiarize myself with the inner workings of asdf and dig deeper right now. If I can help test something, let me know.
