### ISSUE TITLE
Add shims to graalvm executables

### ISSUE THREAD

**Issue by jonatan-ivanov** [asdf-vm/asdf#1089]
### Is your feature request related to a problem? Please describe

asdf-java supports GraalVM but it seems there are no shims for the GraalVM related executables.

```bash
❯ native-image
zsh: command not found: native-image
❯ ls $JAVA_HOME/bin/native-image
/Users/jivanov/.asdf/installs/java/graalvm-21.3.0+java11/bin/native-image
```

### Describe the proposed solution

Add executables just like `java`, `javac`, etc. have.

### Describe similar `asdf` features and why they are not sufficient

There is no shim for this.

### Describe other workarounds you've considered

Adding `$JAVA_HOME/bin` to the `PATH` can be considered as a workaround:
```bash
export PATH="$PATH:$JAVA_HOME/bin"
```

**Comment by Stratus3D** [comment]
@jonatan-ivanov I believe your issue is specific to the graalvm plugin, so you should find the issuer tracker for that plugin and raise this issue there. There is the chance you just need to reshim to make the command available. First try reshimming:

```
asdf reshim
```

Then look at your path:

```
type -a native-image
```

In the output you should see the shims path listed first. If this does not work please open an issue on the asdf graalvm plugin issue tracker.
