### ISSUE TITLE
Confusing message when global executable not installed for a different version

### ISSUE THREAD

**Issue by justin808** [asdf-vm/asdf#1207]
### Describe the Bug

Missing global install prints a confusing message:

```
nps --version                                                                                                                             ✹
No preset version installed for command nps
Please install a version by running one of the following:

asdf install nodejs 14.19.1

or add one of the following versions in your config file at /Users/justin/.tool-versions
nodejs 14.19.0
```

### Steps to Reproduce

1. Node version 14.19.0 installed
2. Install globally: `npm install -g nps`
3. Switch to a project that uses Node 14.19.1
4. Run at command line `nps --version`
5. See the error in the bug description.
6. Fix the error by running `npm install -g nps`

### Expected Behaviour

For a missing global, don't create a shim. So a natural "not installed" message shows.

### Actual Behaviour

see bug description

### Environment

```shell
asdf info                                                                                                                                      1 ↵
OS:
Darwin justin-2022-mbp.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.10.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
direnv                       https://github.com/asdf-community/asdf-direnv.git master 016325f
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master f9957f3
ruby                         https://github.com/asdf-vm/asdf-ruby.git master de49662
yarn                         https://github.com/twuni/asdf-yarn.git main 376c540
```
```


### asdf plugins affected (if relevant)

_No response_

**Comment by jthegedus** [comment]
This is expected behaviour. Tools installed via asdf-managed tools are only available when the correct version is selected.

Global tool installation like this is common in scripting language runtimes, like nodejs. As such, most of those plugins have a mechanism to install globals when you run `asdf install <tool> <version>`. `asdf-nodejs` calls these [default npm packages](https://github.com/asdf-vm/asdf-nodejs#default-npm-packages).

As this is expected behaviour, I will close this Issue.
