### ISSUE TITLE
Allow shims to be locked to a specific version of a tool, regardless of `asdf current` values

### ISSUE THREAD

**Issue by offbyone** [asdf-vm/asdf#1360]
### Is your feature request related to a problem? Please describe

I would like to install commands in a specific version of a tool, and make those commands use that version all the time, regardless of if I'm locally overriding that tool in a project. For example, I might do this:

```console
# install a Ruby formatter globally, in whatever my global ruby version is
$ asdf current | grep ruby
ruby            3.0.0           /Users/offbyone/.tool-versions
$ gem install rufo
Successfully installed rufo-0.13.0
Parsing documentation for rufo-0.13.0
Installing ri documentation for rufo-0.13.0
Done installing documentation for rufo after 0 seconds
1 gem installed
$ rufo --version
rufo 0.13.0

# change to my project, which has a different ruby configured:
$ cd projects/my-project
$ asdf current | grep ruby
ruby            3.1.2           /Users/offbyone/github/heaven/.ruby-version
$ rufo --version
No preset version installed for command rufo
Please install a version by running one of the following:

asdf install ruby 3.1.2

or add one of the following versions in your config file at /Users/offbyone/.tool-versions
ruby 3.0.0
```

### Describe the proposed solution

I would like a mechanism to pin a shim, if that's the right term.  I know that I'll always want `rufo` to run using the version I installed it with, not the current ruby. How can I force the shim to be "sticky" as it work, to use a specific selected version no matter what the toolchain is for my project

### Describe similar `asdf` features and why they are not sufficient

I don't know that there's any feature in ASDF that approximates this.

### Describe other workarounds you've considered

There is a Python tool called "pipx" that does this, and who knows, maybe one exists for Ruby as well, but it seems to me that asdf should be able to provide this facility as well.

**Comment by jthegedus** [comment]
I believe `pipx` is similar to `npx` which just uses the current version of `pip` or `npm` to download (and cache) the appropriate package from that ecosystem and execute it.

I would argue those facilities go against the purpose of ensuring everyone on your project is using the same tool. I don't think it is wild to suggest that each person should probably use the same formatter version as well. So for the scenario given, an asdf plugin to pin everyone to the same version of rufo, or installing rufo as a dev dep in the Ruby ecosystem (if that even exists) is a more appropriate solution.

We have seen this with the Nodejs ecosystem and people wanting to install alternative package managers as global binaries with the Node package manager (`npm`). A plugin to maintain the alternative package manager was the easiest solution.

Those specific scenarios aside, I think the argument holds that if some tool is used to affect your codebase, it should live with the codebase and mechanisms to ensure everyone is using the same version should be tracked within the codebase. Thus, a plugin is the suggested (and IMO more appropriate) solution to this dilemma.

**Comment by offbyone** [comment]
Where this gets tricky is in the intersection of code editor / IDE preferences and tool dependencies. My _personal_ example is that I have my editor configured to always format code on save, and the mechanism it uses to determine if it should do so is if it can find the language's formatter on `PATH`. If I install, say, `rufo`, using project A's ruby in `~/.local/bin/rufo` so that I can use a formatter in one project even though the upstream developer does not have it as a dependency, then that binary is going to be on `PATH ` for all of my projects, using the ruby version from project A. Later, in project B, a different ruby is selected using ASDF, but that binary is still on `PATH` and returns an error when invoked, meaning my formatter plugin errors out every time I save.

Essentially what I need is a way to install these tools without asdf's shims being involved, so that they don't ever return with the "No preset version installed for command" error.

**Comment by jthegedus** [comment]
This is not an uncommon scenario.

The recommendation is still to pin `rufo` to your different projects. It is still the case that tools which manipulate your code should be managed alongside your codebase.

Project A and Project B should define the version of the formatter they use so it can be internally consistent. If Project A needs a new version of `rufo` for whatever reason, a global setup requires that you bring this into Project B, which might conflict with other developers, or might introduce some code change which brings about bugs or whatnot when you make your next code change and format at the same time.

The hypotheticals go on, but the idea of `asdf` is to reduce variability by forcing the use of the same versions of tools and pinning them to projects in a sharable way.

I could also see this feature being misused or misunderstood and introducing many out-of-sync issues within a team.

As for the editor formatter scenario, the editor can be configured to look at specific paths for formatters, so you can pin to a specific Ruby installed version of Rufo that way.

There are other IDE/editor scenarios where versions cannot be found because the editors don't re-init their shell instance for new windows of the editor, so sometimes closing and restarting the editor in the specific project directory is required.


Since I think this should be solved with a plugin and pinning to a version for the project, and editors offer a general solution to resolve this in a global way without a plugin, I will close this as we won't be implementing this feature.

Discussion can continue, but unless one of the other core members has other thoughts, we won't be implementing this feature. As always, as we learn more the decision could change in future.

**Comment by Stratus3D** [comment]
@jthegedus addressed everything above, but I want to share my own solution for IDE-specific tools. In generally we want everything locked down to specific versions every project's `.tool-versions` files. But sometimes there are tools that truly are generic and for convenience we want one version used everywhere. I do this with `tmuxinator`, a Ruby gem for managing tmux sessions. To "pin" `tmuxinator` shim to Ruby 2.6.8 I have the following alias defined in [my dotfiles](https://github.com/Stratus3D/dotfiles/blob/master/mixins/aliases#L56-L58):

```bash
# tmuxinator is only installed in default version of Ruby, so we change to the
# home directory to invoke it with the default Ruby.
alias tmuxinator="cd $HOME && tmuxinator"
```

So wherever I invoke `tmuxinator` I'll be sure to invoke tmuxinator with the version of Ruby that is set for my `$HOME` directory, not the project directory. This is another more explicit way of invoking a shim for a specific version is to use the asdf version environment variable:

```bash
alias tmuxinator="ASDF_RUBY_VERSION=2.6.8 tmuxinator"
```

I wrote about this here - http://stratus3d.com/blog/2017/10/01/asdf-tip-global-programs/
