### ISSUE TITLE
bug: `asdf install` fails if `.tool-versions` uses carriage returns

### ISSUE THREAD

**Issue by atmiguel** [asdf-vm/asdf#1476]
### Describe the Bug

It seems like `asdf install` fails whenever the `.tool-versions` file uses carriage returns for newlines.

### Steps to Reproduce

1. Create a `.tool-versions` file with carriage returns: `echo -e 'nodejs 19.6.0\r' > .tool-versions`
2. Run the install: `asdf install`

### Expected Behaviour

I expected asdf to install the nodejs plugin.

### Actual Behaviour

I got the following error:
```
Trying to update node-build... ok
node-build: definition not found: 19.6.0
```

### Environment

```shell
OS:
Darwin Adrians-Preemo-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.11.1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
gcloud                       https://github.com/jthegedus/asdf-gcloud main 31b3bea
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master c9e5df4
poetry                       https://github.com/asdf-community/asdf-poetry.git master ff6c368
python                       https://github.com/danhper/asdf-python.git master 8505457
terraform                    https://github.com/asdf-community/asdf-hashicorp.git master c44c314
yarn                         https://github.com/twuni/asdf-yarn.git main 376c540
```

**Comment by jthegedus** [comment]
asdf should only be expected to work in Unix environments where carriage returns are not commonly used. We could add a check for this and error specifically for this. But I do not think we want to silently ignore carriage returns.

**Comment by jthegedus** [comment]
I use asdf on macOS, Ubuntu via WSL2 & Ubuntu natively on a regular basis and have never had an issue with this. What I suspect has happened is the user on the Windows machine edited the file, or cloned the repo, from a non-WSL location, and thus, Windows put the carriage returns in. I would guess the difference you're seeing is not a difference between versions.

IMO, while this issue is surfaced by asdf as an error it is not a bug, but rather an indicator of a misconfiguration of the local environment. We can error in a better way, but I feel ignoring carriage returns is the wrong solution.

**Comment by jthegedus** [comment]
My thought process is this:
- we have seen people have this issue before, it was due to their local env and not asdf
- if this was because of the code change it would affect every user since `v0.8.1` which was May 2021, so we would have had hundreds of people reporting this issue

Given that this issue has only just opened, and doesn't have hundreds of upvotes, I tend to think the first scenario is likely.

As I said, I think there is a solution here, but I think it is to error when we detect carriage returns, not ignore them, because it might just error elsewhere.
