### ISSUE TITLE
How do I remove ASDF

### ISSUE THREAD

**Issue by jalcock501** [asdf-vm/asdf#1484]
### How can we improve the documentation?

Just as bad as the pyenv docs: `ASDF` worms its way into pretty much everything, where is the documentation to remove it?

Or should I just nuke my OS now?

**Comment by jthegedus** [comment]
We have a whole section in the documentation site on uninstalling - https://asdf-vm.com/manage/core.html#uninstall

It is basically the reverse of the installation steps. There are generally 3 steps:
1. remove from your Shell
2. remove `.asdf` dir
3. remove config files in your projects and `$HOME`

The docs enumerate most of the setups we have install guides for.

We specifically do not auto configure any part of your system so it is clear what asdf does with your system. The fact people have to manually do things instead of a curl-bash is the majority of the complaints.

If you have genuine feedback on asdf or how to improve the uninstall part of the documentation site we're happy to have it.

**Comment by tzaffi** [comment]
> ### How can we improve the documentation?
> Just as bad as the pyenv docs: `ASDF` worms its way into pretty much everything, where is the documentation to remove it?
> 
> Or should I just nuke my OS now?

Behaves more like a virus than a unix tool.

**Comment by tzaffi** [comment]
> We have a whole section in the documentation site on uninstalling - https://asdf-vm.com/manage/core.html#uninstall
> 
> It is basically the reverse of the installation steps. There are generally 3 steps:
> 
> 1. remove from your Shell
> 2. remove `.asdf` dir
> 3. remove config files in your projects and `$HOME`
> 
> The docs enumerate most of the setups we have install guides for.
> 
> We specifically do not auto configure any part of your system so it is clear what asdf does with your system. The fact people have to manually do things instead of a curl-bash is the majority of the complaints.
> 
> If you have genuine feedback on asdf or how to improve the uninstall part of the documentation site we're happy to have it.

Genuine feedback. Refactor your codebase so that a single command works to uninstall every trace of asdf from every platform that you support.

The instructions you linked to haven't worked for me ...thus far. But I shouldn't need to experiment with 20 different permutations of your commands to delete an install from my system.
