### ISSUE TITLE
Publish an asdf container image in dockerhub every release

### ISSUE THREAD

**Issue by lmilbaum** [asdf-vm/asdf#1487]
### Is your feature request related to a problem? Please describe

Publishing a container image with tags aligned to asdf releases may help renovate identify new asdf releases when it is baked into a layered container image.

### Describe the proposed solution

Every time asdf is released a container image is built with aligned tag and pushed to public registry like ghcr or/and dockerhub

### Describe similar `asdf` features and why they are not sufficient

I would like my project kept updated with the latest and greatest asdf release. As of now I clone this repo and hard code the release tag. 
Every time there is a new asdf release, I manually go to my project and contribute a change.

### Describe other workarounds you've considered

I didn't find any alternative which is not manual

**Comment by jthegedus** [comment]
Hi @lmilbaum 

Are you able to share a minimal code snippet for how you want to use such a container? I am unfamiliar with Renovate and how it integrates with Docker layers.

Are the asdf GitHub Actions not usable in your CI pipeline?

**Comment by lmilbaum** [comment]
> Hi @lmilbaum
> 
> Are you able to share a minimal code snippet for how you want to use such a container? I am unfamiliar with Renovate and how it integrates with Docker layers.
> 
> Are the asdf GitHub Actions not usable in your CI pipeline?

TBH, I found a way to to automate my use case in a different way. See [here](https://github.com/platform-engineering-org/helper/blob/main/Dockerfile). I assume if an asdf image would exist with all of its plugins, I could just somehow use it for the tools installations during build time without installing asdf and its plugins.

**Comment by jthegedus** [comment]
@lmilbaum Thanks for reporting back here.

I don't think we should produce an image with every plugin in it for these reasons:
- the permutations of what would constitute a new build would be each plugin change
- plugins can be pinned to a specific plugin repo SHA, though it is a 2 step process, I'm working on getting a fix for this in soon
- plugins aren't considered secure by us, users should vet the plugins, so installing without the direct URL format is discouraged

As for your solution, to make it future-proof, I would suggest using `asdf plugin add terraform <url>` form to add plugins. We (asdf core team) consider the plugin repo to be a user-convenience and is something we might remove in future. The compact version of adding a plugin which uses the plugin repo and not the plugin URL directly is not recommended in scripts or building images.

If we were to release a Docker image of `asdf` it would be without any plugins and that would be something users would add and install in their own layers.

Another component to this is that you should be able to use our GitHub Action in other CI pipelines. It has been a long time since I have done this, so I suspect it still works. We could probably document how to do this in some other CI environments.

I will close this for now as the workaround you have shared here is basically how we expect people to use `asdf` when not using our GitHub Action.
