### ISSUE TITLE
bug: Command not found: complete on Macos 13.4.1

### ISSUE THREAD

**Issue by ducpt1012** [asdf-vm/asdf#1596]
### Describe the Bug

.asdf/completions/asdf.bash:89: command not found: complete

### Steps to Reproduce

cd
git clone https://github.com/excid3/asdf.git ~/.asdf
echo '. "$HOME/.asdf/asdf.sh"' >> ~/.zshrc
echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.zshrc
echo 'legacy_version_file = yes' >> ~/.asdfrc
exec $SHELL

### Expected Behaviour

It displays this notice
.asdf/completions/asdf.bash:89: command not found: complete

### Actual Behaviour

N/A

### Environment

```shell
OS:
Darwin XXXX-MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

SHELL:
zsh 5.9 (x86_64-apple-darwin22.0)

BASH VERSION:
3.2.57(1)-release

ASDF VERSION:
v0.11.3-2f55f93

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/Users/xxx/.asdf
ASDF_DIR=/Users/xxx/.asdf
ASDF_CONFIG_FILE=/Users/duc.pt/.asdfrc

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 4f8aa3d
ruby                         https://github.com/asdf-vm/asdf-ruby.git master bca6f3b
```

**Comment by hyperupcall** [comment]
Are your installation steps from the official documentation?

The `echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.zshrc` write command tells _zsh_ to source a Bash-specific completion file. To do this, you must either [enable bashcompinit](https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh) if you really need to use the Bash completion file. Otherwise, you would append to `fpath` as shown [on the website](https://asdf-vm.com/guide/getting-started.html)

**Comment by joeteerawit** [comment]
I'm install using `fish & homebrew` it doesn't work at all.
my work around solution is edit this file `~/.vscode/extensions/jakebecker.elixir-ls-0.15.3/elixir-ls-release/launch.sh` then change `ASDF_DIR=${ASDF_DIR:-"${HOME}/.asdf"}` to `ASDF_DIR=${ASDF_DIR:-"/opt/homebrew/opt/asdf/libexec"}` then restart vscode again

`ASDF_DIR`

**Comment by hyperupcall** [comment]
I'm pretty sure if you add `ASDF_DIR=${ASDF_DIR:-"/opt/homebrew/opt/asdf/libexec` to your shell startup file (or a Fish equivalent command for Fish), and then log out and then log in your computer, the environment variable should be set in in vscode

Related to #1584
