### ISSUE TITLE
Isn't work in termux

### ISSUE THREAD

**Issue by Stu75e** [asdf-vm/asdf#1630]
asdf install python 3.9.18
Downloading python-build...
Cloning into '/data/data/com.termux/files/home/.asdf/plugins/python/pyenv'...
remote: Enumerating objects: 23384, done.
remote: Counting objects: 100% (1834/1834), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 23384 (delta 1722), reused 1700 (delta 1652), pack-reused 21550
Receiving objects: 100% (23384/23384), 4.66 MiB | 2.70 MiB/s, done.
Resolving deltas: 100% (15893/15893), done.
python-build 3.9.18 /data/data/com.termux/files/home/.asdf/installs/python/3.9.18
Downloading Python-3.9.18.tar.xz...
-> https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tar.xz
Installing Python-3.9.18...

BUILD FAILED (Linux 4.14.113-24323734 using python-build 2.3.25-6-g91002438)

Inspect or clean up the working tree at /data/data/com.termux/files/usr/tmp/python-build.20230904211745.3387
Results logged to /data/data/com.termux/files/usr/tmp/python-build.20230904211745.3387.log

Last 10 log lines:
3 warnings generated.
gcc -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -DOPENSSL_NO_SSL3   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include -I/data/data/com.termux/files/home/.asdf/installs/python/3.9.18/include -I/data/data/com.termux/files/home/.asdf/installs/python/3.9.18/include -fPIC -DPy_BUILD_CORE -o Python/traceback.o Python/traceback.c
gcc -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -DOPENSSL_NO_SSL3   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include -I/data/data/com.termux/files/home/.asdf/installs/python/3.9.18/include -I/data/data/com.termux/files/home/.asdf/installs/python/3.9.18/include -fPIC -DPy_BUILD_CORE -o Python/getopt.o Python/getopt.c
In file included from Python/thread.c:80:
Python/thread_pthread.h:473:33: error: call to undeclared function 'sem_clockwait'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            status = fix_status(sem_clockwait(thelock, CLOCK_MONOTONIC,
                                ^
1 error generated.
make: *** [Makefile:1803: Python/thread.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by hyperupcall** [comment]
In the future, please [format your code](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks).

Since this is specifically an error with compiling Python, this error should be reported in [asdf-python](https://github.com/asdf-community/asdf-python). But as far as I can tell, this is not an asdf issue. asdf doesn't magically know how to compile Python for all packages, so you need to help it a little by supplying the right override flags to autoconf or gcc.

**Comment by VectorASD** [comment]
Для начала, нужно правильно собрать:

make distclean
bash configure --prefix=$PREFIX --enable-optimizations
$PREFIX нужен для того, чтобы make install понимал, куда ставить результат сборки
--enable-optimizations просто был всегда при написании данного ответа

Полезным будет использовать make -j$(nproc) вместо просто make, что позволяет распределить нагрузку между всеми моими 8 ядрами, вместо того, что всё в одно пихать
Ошибка отсутствия ar архиватор, используйте:
pkg install binutils (если компилили через gcc)
pkg install binutils-is-llvm (если компилили через clang)

В рабочей дирректории репозиторя есть файлик pyconfig.h

Просто допишите в конец (либо, как я, ищите каждый параметр вручную, закомментируйте сами #define ...):

#undef HAVE_SEM_CLOCKWAIT
#undef HAVE_PTHREAD_GETNAME_NP
#undef HAVE_PTHREAD_SETNAME_NP
// Один лишь Modules/posixmodule.c нарожал этих ошибок:
#undef HAVE_STATX
#undef HAVE_FEXECVE
#undef HAVE_GETLOGIN_R
#undef HAVE_GETLOADAVG
#undef HAVE_PWRITEV2
#undef HAVE_PREADV2
#undef HAVE_GETPWENT

Это особенность termux: компилятор gcc просто не снабжён функциями ;"-} Если будут проблемы, сами по коду смотрите какие #if или #ifdef позволяют туда попадать. Обычно имя неимеющегося символа дублируется в переменную после HAVE_

Ещё есть ловушка:
#define HAVE_PTHREAD_GETNAME_NP 0 НЕ СРАБОТАЕТ
а вот
#undef HAVE_PTHREAD_GETNAME_NP СРАБОТАЕТ
думал, что разработчики сильно накосячили, а на практике надо проверять концовку комментария: ", and to 0 if you don't.", что стоит перед #define, хоть это и не всегда объективно, т.к. на деле разные разработчики просто недоговорились...

Запуск питона из корневой дирректории cpython репозитория: ./python
Если прописать просто python, запустится 3.12.9 версия, что является последней в termux на момент написания данного ответа.

Грубый, но рабочий способ перезаписи, т.е. без make install, pgo и симлинка (только на текущую сессию и без поддержки pip):
~/cpython $ export PATH="$PWD:$PATH"
~/cpython $ python --version
Python 3.15.0a1+

На этапе тестирования, проверка некоторых модулей провалилась, а 41/43 тест вообще свалил весь процесс тестировщика, т.к. нарвался на безопасность андроида.
Проверка re:
Python 3.15.0a1+ (main, Oct 25 2025, 04:47:07) [Clang 20.1.2 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> dir(re)
['A', 'ASCII', 'DEBUG', 'DOTALL', 'I', ...даю добро на правдивость вывода
>>> print(re.findall(r'\d+', 'abc123def456'))
['123', '456']
Как мы видим, сам re работает. Ошибка теста заключалась в том, что был вызван fork, либо подобная специфичная операция, не свойственная андроиду, так что игнорируем.

Перед make install нужно удалить в Lib/test/libregrtest/pgo.py все тесты, что валятся, при том, 'test_time' вообще валит процесс (можно хоть все снести, но для вида лучше первые 7 оставить, они быстро срабатывают и все зелёные). Это позволит вам сохранить режим --pgo, что и пораждается опцией --enable-optimizations, но при этом установить питон, как надо!
Это нормально, что сборка повторится... и без -j параметра :/ Зато питон будет хорошо оптимизирован ;'-}

Симлинки:
ln -sf $PREFIX/bin/python3.15 $PREFIX/bin/python
ln -sf $PREFIX/bin/pip3.15 $PREFIX/bin/pip

Проверка, желательно, вне cpython репозитория ;'-}
python --version
pip --version

На момент написания комментария, билдил python3.15.0a1

**Comment by VectorASD** [comment]
## 🛠️ Initial Setup

To begin, you need to build Python correctly:

```bash
make distclean
bash configure --prefix=$PREFIX --enable-optimizations
```

- `$PREFIX` is needed so that `make install` knows where to place the build output.
- `--enable-optimizations` is always used throughout this guide.

---

## ⚡ Use Parallel Compilation

It's useful to run:

```bash
make -j$(nproc)
```

This distributes the load across all 8 of my CPU cores, instead of funneling everything into a single thread.

---

## 🧱 Missing `ar` Archiver

If you encounter an error about a missing `ar` archiver, install the appropriate package:

- For GCC builds:  
  ```bash
  pkg install binutils
  ```

- For Clang builds:  
  ```bash
  pkg install binutils-is-llvm
  ```

---

## ⚙️ Fixing Platform-Specific Issues

In the working directory of the CPython repository, there's a file called `pyconfig.h`.

Just append the following lines to the end (or, like I did, search for each parameter manually and comment out the corresponding `#define`):

```c
#undef HAVE_SEM_CLOCKWAIT
#undef HAVE_PTHREAD_GETNAME_NP
#undef HAVE_PTHREAD_SETNAME_NP
// These errors were mostly triggered by Modules/posixmodule.c:
#undef HAVE_STATX
#undef HAVE_FEXECVE
#undef HAVE_GETLOGIN_R
#undef HAVE_GETLOADAVG
#undef HAVE_PWRITEV2
#undef HAVE_PREADV2
#undef HAVE_GETPWENT
```

This is a Termux-specific issue: the GCC compiler simply lacks these functions 😅  
If you run into problems, inspect the code and look for `#if` or `#ifdef` blocks — usually the missing symbol name is mirrored in a `HAVE_` macro.

---

## ⚠️ Gotcha: `#define ... 0` Doesn’t Work

```c
#define HAVE_PTHREAD_GETNAME_NP 0  // ❌ Doesn't work
#undef HAVE_PTHREAD_GETNAME_NP     // ✅ Works
```

I thought the developers messed up, but in reality, you need to check the comment ending with:  
`", and to 0 if you don't."` — which precedes the `#define`.  
Still, this isn’t always reliable, since different developers interpret it differently.

---

## 🐍 Running Python from the CPython Repo

To run the freshly built Python:

```bash
./python
```

If you just type `python`, it will launch Termux’s default version — currently 3.12.9 at the time of writing.

---

## 🧪 Crude but Working Override (No `make install`, no PGO, no symlinks)

```bash
export PATH="$PWD:$PATH"
python --version
# Output: Python 3.15.0a1+
```

This works only for the current session and doesn’t support `pip`.

---

## 🧪 Testing Notes

During testing, some modules failed. Test 41/43 even crashed the test runner due to Android security restrictions.

Example: testing `re`

```python
>>> import re
>>> dir(re)
['A', 'ASCII', 'DEBUG', 'DOTALL', 'I', ...]
>>> print(re.findall(r'\d+', 'abc123def456'))
['123', '456']
```

As you can see, `re` works fine. The test failure was due to a `fork()` or similar system call not supported on Android — so we can safely ignore it.

---

## 🧹 Cleaning Up PGO Tests Before `make install`

Before running `make install`, go to:

```
Lib/test/libregrtest/pgo.py
```

Delete all tests that fail. In particular, `'test_time'` crashes the process entirely.  
You can remove all tests, but it’s better to leave the first 7 — they run quickly and pass.

This lets you keep `--pgo` mode (enabled via `--enable-optimizations`) while still installing Python properly.

Yes, the build will repeat… and without the `-j` flag 😅  
But the resulting Python will be well optimized 😉

---

## 🔗 Symlinks

```bash
ln -sf $PREFIX/bin/python3.15 $PREFIX/bin/python
ln -sf $PREFIX/bin/pip3.15 $PREFIX/bin/pip
```

---

## ✅ Final Check (Outside the CPython Repo)

```bash
python --version
pip --version
```

At the time of writing, I built Python 3.15.0a1.

Translated (RU->ENG) and markdowned with AI ;'-}
