### ISSUE TITLE
recursive upward search

### ISSUE THREAD

**Issue by danielb2** [asdf-vm/asdf#1707]
### Is your feature request related to a problem? Please describe

I've got a work project and not everyone uses asdf and I don't want to "pollute" the git repo with a .tool-versions. direnv is already used by the project.

### Describe the proposed solution

Do recursive upward search to to find the first .tool-version available and use the versions there

### Describe similar `asdf` features and why they are not sufficient

- `$HOME/.tool-versions` is too general
- `direnv` is already used by the project and I don't want to pollute that file
- using a local .tool-versions would also pollute the project unless I add to .gitignore. but there are multiple projects and a recursive upward search would make it much easier as I don't have to commit files to work around it

### Describe other workarounds you've considered

I could mess with .gitignore for every single project I have. both for work and other projects.

**Comment by jthegedus** [comment]
`$HOME/.tool-versions` is not a specific "global" implementation, we already recursively look up directories and typically find `$HOME/.tool-versions` as most people work within their `$HOME` dir.

My solution to this exact problem is to put a `.tool-versions` file in a shared work project directory. Eg:

```
$HOME
     /dev
         /dotfiles
     /work
         .tool-versions
         /project1
         /project2
```

so when working in `project1` or `project2` the `$HOME/work/.tool-versions` is used.

Other options include `.gitignore` `.tool-versions` files from your global settings if it appears under a work directory.

---

Since this is already how asdf works, and there are solutions to this particular scenario, I am going to close this issue.

**Comment by danielb2** [comment]
@jthegedus you're right. I'm not sure what I did wrong yesterday. Thank you
