### ISSUE TITLE
Issue with Circle CI and asdf

### ISSUE THREAD

**Issue by digitalcake** [asdf-vm/asdf#185]
EDIT:  This was a noob mistake. 

I thought the plugin added a file called .tool-version, not realizing I needed to have it. 

This was resolved by adding the needed .tools-version file as I specified in my `awk '/erlang/ { print $2 }' .tool-versions` command. 

I'm hitting an issue with 
```
erlang_version=$(awk '/erlang/ { print $2 }' .tool-versions) && asdf install erlang ${erlang_version}
awk: fatal: cannot open file `.tool-versions' for reading (No such file or directory)

erlang_version=$(awk '/erlang/ { print $2 }' .tool-versions) && asdf install erlang ${erlang_version} returned exit code 2

Action failed: erlang_version=$(awk '/erlang/ { print $2 }' .tool-versions) && asdf install erlang ${erlang_version}
```

Heres my steps to get there. 
```
pre:
    - if ! asdf | grep version; then git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.3.0; fi
    - asdf plugin-add erlang https://github.com/HashNuke/asdf-erlang.git
    - asdf plugin-add elixir https://github.com/HashNuke/asdf-elixir.git
    - erlang_version=$(awk '/erlang/ { print $2 }' .tool-versions) && asdf install erlang ${erlang_version}
    - elixir_version=$(awk '/elixir/ { print $2 }' .tool-versions) && asdf install elixir ${elixir_version}
    - mix local.rebar --force
    - yes | mix deps.get
```

**Comment by Stratus3D** [comment]
I'm not familiar with Circle CI, but it seems like the real issue here is the lack of a `.tool-versions` file (according to the awk error you don't have one in your repo/build). If you have a `.tool-versions` file in the root of your repo/build, then a simple `asdf install` should suffice. The `erlang_version=$(awk '/erlang/ { print $2 }' .tool-versions) && asdf install erlang ${erlang_version}` lines should not be necessary.

**Comment by digitalcake** [comment]
yeah sorry I should have updated this. I figured that out. Thats for the follow up any how. Thank for the plugin :) 👍
