### ISSUE TITLE
Supported legacy version list.

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#225]
It would be great to have a list in the Readme/wiki about which legacy version files are supported by asdf so I can know which existing projects of mine are compatible. Are the individual plugins required to specify which version formats they support or is this done at the asdf core level?

If someone is able to point me to the right place I'm more than happy to take the time to compile the list myself and update the docs/wiki!

**Comment by Stratus3D** [comment]
asdf only provides an API for plugins to add support for various version files. Plugins must include the necessary callback scripts in order to support additional version files besides `.tool-versions`. See the plugin guide for the details on these callback scripts https://github.com/asdf-vm/asdf/blob/master/docs/creating-plugins.md.

**Comment by Stratus3D** [comment]
So to answer your question, legacy version file support is defined in the plugins themselves. If you want to document the supported version files that should be done in the plugin's README/wiki. Closing since this isn't a feature or bug for asdf (unless we want to expose the return value of the `bin/list-legacy-filenames` callback script to the end user or something like that).

**Comment by jthegedus** [comment]
Thanks for your time answering this.
