### ISSUE TITLE
Readme is broken for adding plugins

### ISSUE THREAD

**Issue by hex0cter** [asdf-vm/asdf#229]
### Steps to reproduce
git-url appears mandatory when adding a plugin which is included in https://github.com/asdf-vm/asdf-plugins
```bash
ᐅᐅ asdf plugin-add Python
usage: asdf plugin-add <name> <git-url>
 ᐅᐅ asdf plugin-add python
usage: asdf plugin-add <name> <git-url>
```

This is not consistent as what is described in the readme.

Tell us what actions you performed before the issue occurred

### Expected behavior

Tell us what should have happened

### Actual behavior

Tell us what happened instead

### Environment

**OS**:
macOS

**asdf version**:
git hash: d3a66d78ee60322609967846142d5fd56ffe6a2f

**Comment by tuvistavie** [comment]
The README is the documentation for the master branch, which has not been released yet.
You can check the documentation for 0.3, the latest published version, here:
https://github.com/asdf-vm/asdf/tree/v0.3.0
Otherwise, if you want to use the master branch, you can use `asdf update --head`.
We should probably add a note about it in the README to avoid confusing users, so I will leave this issue open until we do so.

**Comment by Stratus3D** [comment]
Hi @hex0cter , the readme describes the latest changes in the master branch, but you have the latest release which is far behind master right now, so that functionality isn't present. The current release still requires a git URL.

I'm going to tag a new release as soon as #227 is merged so hopefully it won't be much longer until this is released.

**Comment by hex0cter** [comment]
Thanks @tuvistavie and @Stratus3D ! I figured out how it works soon after this issue was opened. Agree on adding a note in the readme so new comers won't be confused. Thanks for taking care of this!
