### ISSUE TITLE
asdf is using the version specified in current directory tool-versions file when running a file in another directory that has a tool versions file in it.

### ISSUE THREAD

**Issue by relapi** [asdf-vm/asdf#289]
### Steps to reproduce

Tell us what actions you performed before the issue occurred

### Expected behavior

Tell us what should have happened

- I'm in `/blah/test/` w/ a `.tool-versions` file specifying ruby 2.3.
- In `/huh` there is a file `script`, a ruby script with `#!/usr/bin/env ruby` and a `.tool-versions` file specifying ruby 2.5
- `/huh` is in my PATH
- Running `script` while in `/blah/test/` executes the file with Ruby 2.5

### Actual behavior

Tell us what happened instead
- Running `script` while in `/blah/test/` executes the file with Ruby 2.3

### Environment

**OS**: 10.13.3

**asdf version**: 0.4.2

**Comment by Stratus3D** [comment]
Thanks for the report, but this is expected behavior. asdf infers the version based off of the current working directory. Right now we don't have any work arounds for this limitation, but I'd recommend you change to that other directory before running the script:

```
$(cd /huh/; ./script)
```

If this is something you will do often an shell alias could also be helpful.
