### ISSUE TITLE
Any plans for PHP?

### ISSUE THREAD

**Issue by rstacruz** [asdf-vm/asdf#29]
¯\\\_(ツ)_/¯

**Comment by Stratus3D** [comment]
I just started a PHP plugin: https://github.com/Stratus3D/asdf-php. Creating a plugin is simple so I will hopefully have this plugin finished today.

**Comment by HashNuke** [comment]
@Stratus3D <3 :+1:

**Comment by HashNuke** [comment]
@Stratus3d b/w no hurry.

**Comment by HashNuke** [comment]
Marking this issue as "help wanted". Anyone looking to contribute, please contribute directly to @Stratus3D's repository here - https://github.com/Stratus3D/asdf-php

**Comment by belaustegui** [comment]
This is so great :heart:

**Comment by odarriba** [comment]
I've created a plugin (based on @Stratus3D code) that works fine at least in OSX and Ubuntu.
It has been tested installing PHP 7.x.x and 5.6.x, so more testing would be appreciated.

https://github.com/odarriba/asdf-php

**Comment by belaustegui** [comment]
Works wonderfull on a Symfony 2.8 installation with Sylius. Good job! :+1:

**Comment by Stratus3D** [comment]
That's awesome! As you have seen, I really dropped the ball with asdf-php. I don't use PHP regularly so I wasn't motivated to finish it.

I'd like to list this plugin in the asdf readme, but the plugin must pass asdf's plugin-test command first. Can you setup a travis CI build for the repository? It's really easy to do. Here is the `.travis.yml` file from my asdf-lua plugin: https://github.com/Stratus3D/asdf-lua/blob/master/.travis.yml

I'll do some testing of the plugin myself and let you know if I find any issues. I'd also like to remove my asdf-php repository to make it clear that yours is the canonical PHP plugin and to avoid confusing future asdf users. I will delete mine once you setup the Travis build.

Thanks!

**Comment by odarriba** [comment]
I've successfully added TravisCI to the repository.

Just saying that I encounter a big issue with Travis: the OSX public IP was temporarily banned from Github API due to quota exceed. To solve it, I have added the possibility of using custom GitHub credentials via environment variables (and added them using secret env variables of Travis).

Hope this can make this repository added to official README ! :)

**Comment by odarriba** [comment]
And I have also added information of that issue and how to solve it in the README of the repo.

**Comment by HashNuke** [comment]
@odarriba Thank you for the plugin. Can you send a PR to add it to the plugin list on the readme?

**Comment by rstacruz** [comment]
Nice work everyone! 😍

**Comment by belaustegui** [comment]
The dependencies for PHP compilation should be added along with the dependencies for the rest of the packages?

**Comment by Stratus3D** [comment]
@odarriba do you want that secret environment variable checked into the asdf-php repo? That seems like it would contain your login credentials.

**Comment by Stratus3D** [comment]
@belaustegui I think PHP dependencies should remain separate from asdf dependencies if that's what you mean. Many asdf plugins have additional dependencies.

**Comment by Stratus3D** [comment]
@odarriba I just deleted my repo, now yours is no longer a fork.

**Comment by odarriba** [comment]
@Stratus3D As I have read, that secure env variable is the recommended method by Travis to store credentials and so on. It uses a pair of RSA keys to store credentials securely, so only Travis con read them.

If I don't use it, it can produce errors since the build servers can be banned from Github API (as occurred in the OSX build of PHP plugin).

**Comment by odarriba** [comment]
More info: https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
