### ISSUE TITLE
Use exit code 127 on missing version

### ISSUE THREAD

**Issue by endorama** [asdf-vm/asdf#305]
Hello, 

first of all thank you for this project. I'm using `asdf` since a couple of month and is really awesome! There is little thing that I think could be improved, and I can provide a PR if you're interested.

Currently when you install a plugin it adds a shim in the path. This makes impossible to test if the command is available using "usual" checks, because is always available.
Currently after displaying the error message the command exists with [`-1` or `1`](https://github.com/asdf-vm/asdf/search?utf8=%E2%9C%93&q=display_no_version_set&type=). 
The Advanced BASH Scripting guide has some [codes with special meaning](http://tldp.org/LDP/abs/html/exitcodes.html), and from my searches seems to be the *de-facto* standard for exit codes in shell scripting ( even zsh uses the `127` for missing commands ).

What is the reason for the current behaviour? Could be aligned with the special exit codes from the BASH Scripting guide ( thus using `127` as exit code if no version is found )? Thank you.

### Steps to reproduce

- Install a plugin ( es `kops` )
- Run any plugin with no version set

### Expected behavior

- Warning message is printed
- Exit code is `127`

### Actual behavior

- Warning message is printed
- Exit code is `255` or `1`

### Environment

**OS**: Ubuntu 16.04

**asdf version**: v0.4.3

**Comment by Stratus3D** [comment]
@endorama yes those exit codes can be updated. I don't think an exit code of 255 or 1 is wrong per se, but I understand why 127 would make sense. If you create a PR that makes the exit codes more logical I will not object to it. Though because it changes the codes it may not be wise to release it in a patch version. We may need to do a minor release since this could break existing code that integrates with asdf.
