### ISSUE TITLE
Different gemsets?

### ISSUE THREAD

**Issue by rlipscombe** [asdf-vm/asdf#312]
It appears that Ruby-ists no longer recommend gemsets (you're supposed to use `bundle exec`), but rvm still supports them, and we still use them. Also, `bundle exec` is extra typing.

Is there any way to persuade asdf to either actually implement rvm-style gemsets, or to fake it (by, e.g., allowing multiple versions of ruby to be installed at the same time, but with some kind of suffix)?

Similarly, virtualenv for Python.

**Comment by Stratus3D** [comment]
I'm not sure this will require any changes to asdf itself. This issue belongs in the [asdf-ruby](https://github.com/asdf-vm/asdf-ruby) project and an issue should only be opened up here if there is something that needs to be changed in asdf to support this feature in asdf-ruby.

I'm not very familiar with gemsets, but the way asdf works you will always have multiple versions of Ruby installed on your system (provided you have installed more than one).

**Comment by Stratus3D** [comment]
Closing this for now. If you find something that needs to be addressed in asdf please reopen this issue.

**Comment by rlipscombe** [comment]
For reference: https://github.com/asdf-vm/asdf-ruby/issues/25

**Comment by morhook** [comment]
What rubyists are recommending to stop using `gemsets` @rlipscombe ?

**Comment by leomao10** [comment]
@morhook I guess your question is why? 

Because the original idea for `gemsets` is create `gemset` per project, but that means even project A and project B using some commond gems(same gem same version), you still have to install the gem again. Which is redundant. So instead, ruby community suggest we are not using gemset, so that gems can be installed per versions, and can be shared across project.

And for what to replace the `gemsets`, bundler and `bundle exec`would fix most of the issues. And if you want to save some extra keystrokes, then alias `bundle exec` to `be` seems to be most common way. Or put your project `bin` folders to path, with help of `direnv` or alike
