### ISSUE TITLE
One failed installation should not halt later installations

### ISSUE THREAD

**Issue by the-mikedavis** [asdf-vm/asdf#320]
### Steps to reproduce

```shell
$ cat .tool-versions
erlang 20.3
elixir 1.6.5-otp-20
$ asdf install
Extracting source code
Building Erlang/OTP 20.3 (asdf_20.3), please wait...
...
[successful installation of erlang]
$ elixir --version
-bash: elixir: command not found
$ asdf install
erlang 20.3 is already installed
/tmp/elixir_build_1HwFcW/elixir-precompiled-1.6.5-otp-20.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4869k  100 4869k    0     0  1575k      0  0:00:03  0:00:03 --:--:-- 1575k
$ elixir --version
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.5 (compiled with OTP 20)
```

### Expected behavior

One call to `asdf install` should install both erlang and elixir (everything in the `.tool-versions`
file).

### Actual behavior

The first call to `asdf install` successfully installed erlang **but not** elixir.
The next call to `asdf install` successfully installed elixir.

### Environment

**OS**: MacOS High Sierra (zsh), Ubuntu 16.04 & Ubuntu 14.04 (bash). All installed through `git clone`.

**asdf version**: v0.4.3

Probably something in [here](https://github.com/asdf-vm/asdf/blob/master/lib/commands/install.sh#L43).

**Comment by Stratus3D** [comment]
This is a bug in asdf-erlang that has been captured in https://github.com/asdf-vm/asdf-erlang/issues/57 and the related tickets.

I guess the question that should be raised here is should a failed install halt all later installs?

**Comment by the-mikedavis** [comment]
Whoops, just saw asdf-vm/asdf-erlang#57 :sweat_smile:

I would vote no to halting. It makes arguable sense if the `.tool-versions` contains only erlang and then elixir, but if it contains something somewhat unrelated like node, it doesn't make too much sense to _not_ install that.

**Comment by Stratus3D** [comment]
I guess I'd vote for halting now that I think about it. If the user is assuming that Erlang 20 will be installed and available when Elixir is installed, and Erlang 20 fails to install first, it will result in Elixir failing to be built, or being built with the wrong Erlang version. If we do install Elixir with the wrong Erlang version, it's worse than not installing either, because the user will then have to remove Elixir before installing the correct Erlang version. We can't know if later packages depend on previous packages, so I feel like we need to assume that all later packages depend on a specific version in the `.tool-versions` file.

Additionally it will be more obvious to the user that something has gone wrong if we halt immediately.

**Comment by the-mikedavis** [comment]
I suppose I'm leaning that way a little, now that I think about it. You can successfully install Elixir without Erlang (because asdf-elixir from the repo gets precompiled binaries), but you can't really do anything useful. Even `iex` fails.

I suppose that since some languages are dependent on each other (Erlang & Elixir, Java & Clojure), it does make sense to fail.

**Comment by Stratus3D** [comment]
Closing this as I think we should stick with the current behavior. Better to be safe than sorry in my view.
