### ISSUE TITLE
Update all?

### ISSUE THREAD

**Issue by jrasanen** [asdf-vm/asdf#35]
Hi,

if you take feature suggestions, it would be nice to have a hook for updating a package & "update all" command.

Thanks!

**Comment by HashNuke** [comment]
Hello @jrasanen,
Yes. Suggestions are always welcome :)
Can you share an example use-case for the hooks?

**Comment by jrasanen** [comment]
@HashNuke Hi, sorry for the late response. Use case being ability to bump multiple packages to the latest stable.

So maybe this could be two new hooks, 1) a hook for a package retrieving if newer version is available and 2) update.

**Comment by HashNuke** [comment]
@jrasanen `asdf plugin-update --all`might be what you are looking for.
Closing this issue. Please do re-open it if you think it wasn't the appropriate answer you were looking for.

**Comment by aaccioly** [comment]
HI @HashNuke, I'm sorry if this has already been implemented, but I guess that the feature that @jrasanen was talking about, and the one that I'm looking for is not about updating plugins, it's about updating every software to it's latest and greatest version.

E.g.:

```
❯ asdf list
bat
  0.21.0
fzf
  0.29.0
golang
  1.18.2
gradle
  7.4.2
hugo
  0.99.0
```

New magical command:

```
❯ asdf update all
   Updating fzf to latest version: 0.30.0...
   Updating gradle to latest version: 7.5-milestone-1...
   Updating hugo to latest version: 0.99.1...
   
   All packages updated
...

```
```
❯ asdf list
bat
  0.21.0
fzf
  0.30.0
golang
  1.18.2
gradle
  7.5-milestone-1
hugo
  0.99.1
```

I could certainly use an `update all` command, or at least a combination of `install latest --all` + `asdf global latest --all`.

I mean, I wrote my own combination of scripts to do this, but it would be nice if this functionality could be part of the main API, so that people that are only interested in the latest and greatest version of the software can use it as a more traditional package manager.

**Comment by v3rm0n** [comment]
Looking for this as well, but not sure if it is possible since how do you define latest and greatest? For example if you list java versions you get `zulu-jre-javafx-18.30.11` as the latest version but this is actually the latest of `zulu-jre-javafx` version of java. If I'm currently using `adoptopenjdk-jre` then it would replace it with a version I don't actually want.
I would llike to get `adoptopenjdk-jre-18.0.1+10` which is quite high up in the list because it starts with `a` 🤔

**Comment by aaccioly** [comment]
@v3rm0n , for an update all it's certainly trickier, but for java itself, I think that you use a prefix (e.g., `adoptopenjdk-jre`) + `latest`.

This would be open way to do it with Java, Python, etc, find the current prefix + install the latest version with this prefix.

**Comment by stealthybox** [comment]
Here is a workaround in shell:
```shell
for tool in $(asdf plugin list); do
  asdf install "${tool}" latest  \
    &&  asdf global "${tool}" latest  \
    &&  echo "${tool} set globally"
done
```

You can add a shell alias for this or put it a script on your path

**Comment by CanRau** [comment]
was also looking for something like `asdf global all latest` or something, for now I just stuffed the loop from @stealthybox in my `upgradeall` function 🤓
