### ISSUE TITLE
Idea: Expose on SETUP a command to set the environment based on all plugins installed

### ISSUE THREAD

**Issue by fcrespo82** [asdf-vm/asdf#384]
### Steps to reproduce

1. Install java and maven plugins and a version of each tool on macOS
2. Run `mvn`

### Expected behavior

`mvn` should run correctly

### Actual behavior

Fails with wrong `JAVA_HOME` environment variable set.

### Environment

**OS**: macOS Mojave

**asdf version**: Head

### Suggestion

What I had in mind is a "replacement" for the **exec-env** feature.

Plugins would expose a set of environment variables that are set when `$HOME/.asdf/asdf.sh` is sourced. Could be as simple as calling **exec-env** for all plugins on the sourcing step, and not when calling the **shim**.

In this case, a plugin like maven would not be concerned to set `JAVA_HOME` for itself. But java plugin, which is indeed its concern. 

I don't know if I made myself very clear, but if you need more clarification, please let me know.

If you like the idea I can make a PR adding it. I just would wait for the approval/denial or discussion on this.

Last but not least, thanks for the version manager. I love it!

**Comment by Stratus3D** [comment]
Why not set `JAVA_HOME` in your `.bashrc` or equivalent file? Having environment variables set in your shell usually isn't a problem. I set `JAVA_HOME` in a file that gets sourced by my `.bashrc`: https://github.com/Stratus3D/dotfiles/blob/master/mixins/path#L17.

**Comment by fcrespo82** [comment]
That's what I've done.

My `.zshrc`
```shell
plugins=($(asdf plugin-list))
for plugin in $plugins; do
  local file="$ASDF_DIR/plugins/$plugin/bin/exec-env"
  if [ -f "$file" ]; then
    $($file)
  fi
done
unset plugin plugins
```

Just thought would be nice to have a way to get this behavior from the version manager. 

So the plugins only set what they should expose and not be aware of the other plugins to work. (like the maven one)

**Comment by jonatan-ivanov** [comment]
@Stratus3D Because it is a hack?
The `JAVA_HOME` environment variable is the contract for a lot of software (not just maven but for a lot of other ones). Java and Softwares using Java aren't the only ones who are depending on such a contract (i.e.: using environment variables).

This means that without having a hook for the plugins in which they can modify the environment variables, all of the plugins which manage an environment-sensitive software are practically broken.

@vic @danhper What do you think?

**Comment by jthegedus** [comment]
https://github.com/halcyon/asdf-java has specific instructions on how to work with `JAVA_HOME`. Issue https://github.com/halcyon/asdf-java/issues/51 linked to this Issue, but has since been resolved within the plugin and after the last comments on this thread, so I believe the problem may have been resolved.

I will close for now as this doesn't appear to be pressing. Feel free to continue the discussion and/or reopen.
