### ISSUE TITLE
`asdf_updates_disabled` missing from Brew installations

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#412]
```
fatal: not a git repository (or any of the parent directories): .git
```

I looked through the git blame for `asdf_updates_disabled`—my guess is that the intention was for homebrew to drop a file with that name in with the repo during installation, but from what I can tell, that doesn't actually happen. I couldn't find any reference in this repo or the homebrew formula to creating this file, so it seems likely it was just missed.

Since the fix in this PR reports the same error for any non-git installation, which includes homebrew, this should be the fix. In theory we might not need the `asdf_updates_disabled` check anymore, but I figured it could be better for backward compatibility to keep it just in case I missed anything, and there isn't really a downside apart from the maintenance cost of an extra piece of logic in the code.

_Originally posted by @rliebz in https://github.com/asdf-vm/asdf/pull/411#issuecomment-443573230_

**Comment by rliebz** [comment]
In theory #411 already fixes the homebrew behavior to be correct. So we have three options here:

- Leave it as is, because it should work, even if no one is currently using `asdf_updates_disabled`
- Remove the `asdf_updates_disabled` check and just use the check for _any_ non-git repo, which includes homebrew installations. This keeps the code simplest long-term
- Add `asdf_updates_disabled` to Homebrew to explicitly opt in to no `update` functionality, rather than relying on the fact that it's not a `git` repo

**Comment by Stratus3D** [comment]
@rliebz you are right. #411 should be sufficient.
