### ISSUE TITLE
Setting build options in .tool-versions file

### ISSUE THREAD

**Issue by dideler** [asdf-vm/asdf#413]
Is it possible to specify build options as environment variables in `.tools-versions`?

For example

```
KERL_CONFIGURE_OPTIONS="--with-ssl=/usr/local/opt/openssl" erlang 21.1
elixir 1.7.4-otp-21
```

**Comment by Stratus3D** [comment]
It is not possible. There are two reasons for this. First is that build options may need to vary based on OS and developer, whereas versions should generally not. Typically the `.tool-versions` file is checked into version control and shared, which means it not the right place for build options that may vary. Second is that we shouldn't have to worry about trust when reading `.tool-versions` files. Right now we just extract version numbers to the files, and then use them to tell the plugins what versions to install. It isn't possible for a malicious `.tool-versions` file to execute arbitrary code (say downloaded via a Git clone of an unknown repo) on a users computer since nothing in it is evaluated. With environment variables there is the possibility the contents will be evaluated by the code in the plugin or the tool it is installing.

**Comment by dideler** [comment]
Very valid reasons, thanks for explaining!
