### ISSUE TITLE
Show progress bar when downloading

### ISSUE THREAD

**Issue by rhiroyuki** [asdf-vm/asdf#526]
Is it possible to have a progress bar when downloading through asdf?

Some Python versions like Anaconda have like 500mb and can be troublesome to download on unstable network. It would be good to know if asdf is still downloading the file or if it is hanging.

Posting here because it could be applied to all plugins.
What do you guys think?

**Comment by danhper** [comment]
Unfortunately this is not possible because asdf has no idea what the plugins are doing.
At best, we could provide this functionality to use for the plugins and let plugin maintainers decide if they want to use it or not.
For Python unfortunately is would still be impossible because the install is performed by [python-build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build) and asdf-python itself has no idea of what is happening there.
I will keep this open in case somebody else would like to add something.

**Comment by NightMachinary** [comment]
I think it would be a good idea to add a verbose mode, even if plugins need to implement it themselves. The current API encourages silence. My `asdf install julia 1.4.1`s have been hanging and I have no idea why.

**Comment by Stratus3D** [comment]
I created #702 for the idea of a verbose mode. Closing this issue.
