### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by alecmev** [asdf-vm/asdf#527]
[I've packaged asdf for Arch Linux](https://aur.archlinux.org/packages/asdf-vm), looking for feedback.

If you're okay with the existence of this (I assume you are, judging by the presence of Brew) and everything looks fine, maybe it would make sense to mention this package in the docs and have Arch-specific "Add to your Shell" instructions.

I'm also happy to hand over the control of the package to one of the maintainers, since I'm not willing to commit to bumping the version on every release of asdf, but maybe one of you would be okay with that. If nothing major is changed, the procedure takes 30 seconds:

1. Update the version in `PKGBUILD`.
1. Run `updpkgsums`.
1. Run `makepkg --printsrcinfo > .SRCINFO`.
1. Commit and push.

**Comment by danhper** [comment]
Hi, thanks for the package!
I personally would not mind as long as we can integrate it either to our deployment script or preferably the CI.
@asdf-vm/core What do you think?

**Comment by Stratus3D** [comment]
Thanks @jeremejevs !

I personally don't care either way. If we can figure out a way to automate it easily it may be better for us to control the package. Otherwise it may be best for @jeremejevs to control the package and bump the versions whenever he can.

Right now we've got an old homebrew formula that I've been meaning to fix for a while, and haven't gotten around to it because it takes a while to follow the homebrew PR process.

**Comment by jeremejevs** [comment]
At a glance, should be fairly straightforward with [something like this](https://github.com/mikkeloscar/arch-travis) and an AUR SSH key stored somewhere in the secrets. Can't really contribute further than this though, sorry, since I haven't worked with Travis before, and got no insight into your current setup and desires/plans with the CI.

**Comment by HashNuke** [comment]
I have the same opinion as @danhper and @Stratus3D. We can add it to our CI.
Assigning this issue to myself.

**Comment by jthegedus** [comment]
This should be easier now GitHub has Actions and a Package registry

**Comment by jthegedus** [comment]
https://github.com/marketplace?type=actions&query=arch

**Comment by jthegedus** [comment]
@alecmev I see in the comments that `asdf` completions are already handled. Which shell's does this automatically install completions for? I am updating the docs and wish to enter the correct details.

**Comment by alecmev** [comment]
Thanks for updating the docs, @jthegedus! I've left some comments on your PR.

**Comment by izzues** [comment]
Sorry if this isn't the right place to ask this, but are the steps mentioned [here](https://aur.archlinux.org/packages/asdf-vm/) still required?

[alecmev commented on 2020-02-10 11:56](https://aur.archlinux.org/packages/asdf-vm/#comment-728548)
> As mentioned in post_install, please, follow the official instructions to make asdf-vm work, replacing `$HOME/.asdf` with `/opt/asdf-vm`.
> 
> The completions are already installed, just make sure your shell is configured to use them. That is, don't `source completions/asdf.bash` or `fpath=(completions $fpath)`.
> 
> Thanks for bringing this up, `@odelucca`. This is worth highlighting in a pinned comment, installation logs are too noisy.

[odelucca commented on 2020-02-07 14:43](https://aur.archlinux.org/packages/asdf-vm/#comment-728132)
> In order for this package to work, you must add the following on the `~/.bashrc` or `~/.zshrc`:
> 
> ```
> # asdf
> source /opt/asdf-vm/asdf.sh
> source /opt/asdf-vm/completions/asdf.bash
> ```

**Comment by alecmev** [comment]
If you're using Bash, all you need to do is add `source /opt/asdf-vm/asdf.sh` to `~/.bashrc` and make sure you have `bash-completion` installed.
