### ISSUE TITLE
Indicator for official plugin URLs

### ISSUE THREAD

**Issue by x80486** [asdf-vm/asdf#590]
So, today this is the output for this command:

```shell
[x80486@uplink ~]$ asdf plugin-list --urls 
bazel           https://github.com/rajatvig/asdf-bazel.git
docker-slim     https://github.com/everpeace/asdf-docker-slim.git
elm             https://github.com/asdf-community/asdf-elm.git
erlang          https://github.com/asdf-vm/asdf-erlang.git
gohugo          https://bitbucket.org/mgladdish/asdf-gohugo.git
golang          https://github.com/kennyp/asdf-golang.git
gradle          https://github.com/rfrancis/asdf-gradle.git
java            https://github.com/halcyon/asdf-java.git
maven           https://github.com/halcyon/asdf-maven.git
nodejs          https://github.com/asdf-vm/asdf-nodejs.git
rebar           https://github.com/Stratus3D/asdf-rebar.git
shellcheck      https://github.com/Luizm/asdf-shellcheck
terraform       https://github.com/Banno/asdf-hashicorp.git
terraform-validator https://github.com/looztra/asdf-terraform-validator.git
yarn            https://github.com/twuni/asdf-yarn.git
```

I find useful to have an "indicator" somewhere in the output, if possible, that tells whether the URL for a given plugin, matches the URL for the "official" plugin (if that's currently a thing).

Also the aligning is a little bit off with some sausage-named plugins :sunglasses:

**Comment by jthegedus** [comment]
I will look into fixing the alignment.

---

Regarding the indicator for official plugins, that's more difficult. There are 3 distinct places for plugins:

- core adsf team - https://github.com/asdf-vm
- community asdf team - https://github.com/asdf-community
- oss legends on the internet - https://github.com/* (everything else)

Just because something isn't under the asdf banner doesn't mean it isn't good quality and the go-to plugin for that lang/tool. The only things I see it affecting are:

1. the security policy
2. displaying the currently installed plugin, though the current default source URL may have been updated (as is the case with `asdf-java`)

Given that you must already have the plugin installed, I am not sure having a marker here is useful and what message it sends to the plugin community/creators.

**Comment by Stratus3D** [comment]
I agree with @jthegedus. Plugins originate from different places, but the origin is not a good indicator of the quality of the plugin. Even plugins from the core team aren't always up to date, and sometimes lag behind when it comes to best practices. There are plenty of good reasons to chose alternative plugins, so I don't think it makes sense to denote "official" plugins in the output from this command.

**Comment by Stratus3D** [comment]
I am going to close this ticket as it has been 2 months since more input was requested on this issue.

**Comment by jthegedus** [comment]
@Stratus3D I have since thought of some ideas to help resolve this issue, but will raise another discussion as the proposition is more in-depth than an asterisk next to the plugin urls.
