### ISSUE TITLE
Config option to place shims at end of path

### ISSUE THREAD

**Issue by michi-zuri** [asdf-vm/asdf#618]
I would like to have a config option to have shims only at the end of PATH or to leave them out completely. Currently the ~/.asdf/asdf.sh script is rather opinionated about where the shims should be. The ~/.asdf/asdf.sh should respect the choice set in ~/.asdfrc

I propose to add the following option to the configuration:
shims-path = option
Available options would be top [default], end, none

Before I make a pull request with this feature I am hoping for a green light, that this contribution would be welcome.

Rationale: Why would you want to use asdf without shims? There are other options to leverage the version management that doesn't need them, such as the direnv plugin. Shims can get in the way, especially when they shadow system tools. I use the shims at the end of path only for catching the error message that the command is available in asdf, but currently not activated. I don't want to see this error message if a command is available in my PATH behind the shim. Currently the shim intercepts calls to for example `clear` if I have python miniconda installed. 

Making a config option available is the least disruptive way of achieving my goal other than a local-only solution. The more disruptive proposal would be to suggest a change in the behaviour of shims, to default to system if the tool is available on the system. The proposed config option would be opt-in and very easy to implement (only some changes in ~/.asdf/asdf.sh are needed.)

**Comment by vic** [comment]
Regarding the patch, I don't think `~/.asdf/asdf.sh` would need to take options. It's just an utility script to setup the environment for most common use. Just don't source it and place shims directory at the end of your PATH as you already do. And copy the parts from it you might need (like sourcing the asdf function and adding completions to your shell)

And, if I'm understanding correctly, some plugins (`miniconda` in this case) can provide commands like `clear` that are also available in your system. And sometimes you might want to execute the system one instead of the one shipped with `miniconda`.

So, if you have a version of miniconda selected, you want to use their `python` executable but not other executables provided by the package, like their `clear` and you would like to use your system's `clear` instead. Am I right?

Note: For directories where you don't need to activate miniconda, you can make all it's shims resolve to system executables by prodiving the special `system` version in your `.tool-versions` file. However this would only work if you don't need any of the plugin shims. 
```
miniconda system
```

**Comment by michi-zuri** [comment]
> And, if I'm understanding correctly, some plugins (miniconda in this case) can provide commands like clear that are also available in your system. And sometimes you might want to execute the system one instead of the one shipped with miniconda.
> So, if you have a version of miniconda selected, you want to use their python executable but not other executables provided by the package, like their clear and you would like to use your system's clear instead. Am I right?

Not quite: miniconda brings its own set of system tools to have a predictable conda environment. If I am using *conda python I want to use those system tools, but if I'm not in my conda environment, I don't want to be using them. The problem is, that all those conda copies of my system tools will shadow my system tools also when *conda python is not active. This will then trigger the following error message: 
```
mimi$ clear
asdf: No version set for command clear
you might want to add one of the following in your .tool-versions file:

python miniconda3-latest

```

Now I don't want to have to set `python system` in every project that I am not using python, just to be able to use my terminal... I figured out a work-around with direnv, but it could be made easier to setup. 

I don't know if this problem is *conda specific, if it is maybe it should be solved on the *conda level: normally only the conda command lives in path until someone types `conda activate`. But in the asdf python version of *conda everything sits in path even before activation of a conda environment.  

Anyway, I found a working solution for me by moving the shims path to the end manually and using direnv to load active tools to path separately, just wondering how this situation could be improved upstream so that others would never be confronted with this problem. I haven't figured out the best way yet. I just don't think that everyone should figure out custom solutions themselves.

**Comment by jthegedus** [comment]
>Now I don't want to have to set python system in every project that I am not using python, just to be able to use my terminal...

As vic suggested, setting the global `.tool-versions` (usually `~/.tool-versions`) will then be used for all projects where you have not set a specific version.

Nonetheless, I am glad you found a workaround.

**Comment by jthegedus** [comment]
Closing this Issue as:

- there has been no other users requesting or +1 this feature
- it could be a source of bugs or confusion
- the OP posted a workable solution via `asdf-direnv` (thanks for sharing back here)

Should we get more activity on this Issue we can reopen in future.
