### ISSUE TITLE
Command consistency

### ISSUE THREAD

**Issue by jsejcksn** [asdf-vm/asdf#645]
Hi, I'm learning about `asdf` 👋

While I read the documentation, I am seeing similar versions of commands and not sure if they're just the same command with varying syntax or different commands, and it's kind of confusing.

Some examples are:

 - `asdf plugin-add` and `asdf plugin-list` (with a `-`)
 - `asdf plugin add` and `asdf plugin list` (with a ` `)

Perhaps instances of these can be combined/cleaned up (or clarified) in the next minor release?

**Comment by vic** [comment]
Both syntax are equivalent and actually refer to the very same command.

The original syntax for commands was using dashes, eg `plugin-add`. The space syntax is an effort to try normalize the CLI to a more common _subcommand_  interface just like other popular utils do, like `git`, eg `asdf plugin` should include all subcommands for managing plugins and will later display help if you give it no arguments.

But, like I said, both syntaxes are equivalent, since we want to keep backwards compatibility for scripts people already use on their CI environment that use the old dash syntax.

Also, now it's possible for plugins to introduce [new asdf commands and extend asdf funtionality](https://asdf-vm.com/#/plugins-create?id=extension-commands-for-asdf-cli) all of them under the `asdf` command line tool.

Yes, we should update the documentation to reflect the new *space* command syntax. PRs welcome :).

**Comment by jsejcksn** [comment]
@vic Thanks. Based on what you said, I understand that the hyphenated `asdf command-subcommand`s are aliases to specific `asdf command subcommand`s.

Is `shim-versions` the only exception? I'm starting a PR and want to get it right.
