### ISSUE TITLE
Tagged archives not contain zsh completions

### ISSUE THREAD

**Issue by zpdcodes** [asdf-vm/asdf#663]
### Steps to reproduce

Download v0.7.5 and v0.7.6 tar.gz archives from releases. The extracted files neither include `completions/_asdf` nor `completions/_asdf.zsh`.

### Expected behavior

Zsh completions should be inside `completions` folder.

### Links

- https://github.com/asdf-vm/asdf/archive/v0.7.6.tar.gz
- https://github.com/asdf-vm/asdf/archive/v0.7.5.tar.gz

**Comment by jthegedus** [comment]
Native ZSH completions were only merged 5 days ago in https://github.com/asdf-vm/asdf/pull/544. When a new version is cut it should contain them. In the meantime you can update to the head of master with `asdf update --head`

**Comment by zpdcodes** [comment]
@jthegedus Thanks for reply. Sorry I didn't see the PR. GitHub shows months of history for file `completions/_asdf` so I thought it already be there long ago. I'm using [AUR](https://aur.archlinux.org/packages/asdf-vm/) for asdf-vm so I will go with the bash way until new version released.

**Comment by jthegedus** [comment]
No worries mate! You're right that the file is old and I can see how it is confusing without looking at the specific git changes. Native ZSH completions were removed in 2017 due to lack of upkeep. Now macOS Catalina+ is using ZSH and our community is larger it made sense to add them back at the request of our ZSH users.

**Comment by Stratus3D** [comment]
I'm preparing to tag v0.7.7 this week. zsh completions will be present in new v0.7.7 archive.
