### ISSUE TITLE
Optional global/local on install

### ISSUE THREAD

**Issue by lee5i3** [asdf-vm/asdf#685]
Would it be possible to add a optional --global or --local after you install?

For example

```asdf install nodejs 12.16.1 --global```

This would allow us to install and set on one command rather than install then a separate global

**Comment by Stratus3D** [comment]
I think having separate commands for installing and setting versions is better for a couple reasons:

1. They are actually separate things. Installation of versions are unrelated to setting of versions. You can specify a version you don't have installed, and you can install a version that you don't have specified in any of your `.tool-versions` files.
2. Our goal is to keep the interface as simple as possible. The fewer flags each command supports the better. Flags should not be added for convenience sake.
3. Having a flag like `--global` for the `install` command could confuse users about the semantics of asdf. Combining two very different things in one command will result in some confusion.

**Comment by feld** [comment]
Let's say you have an automation / CI pipeline and want to use asdf to install all your toolchain dependencies automagically. You trust your team to use `.tool-versions` to declare what is needed and this should be the single source of truth. How do you set the versions globally so they work for dependencies of your own codebase without having to hardcode commands into a script which need you to declare the versions again? Turns out this is harder than you'd think.

My first attempt was with xargs. Why not read `.tool-versions` and send it through xargs? Turns out this works great on FreeBSD and MacOS because BSD xargs, but behaves differently than GNU xargs.

With GNU xargs the following:

the **.tool-versions** file:
```
rust 1.67.0
```

Ahh, you say,  "We can just do this to read a single line and send it through xargs":

```
cat .tool-versions | awk -F'\n' '{print $0}' | xargs -I{} asdf global {}
```

or so you'd think. But GNU xargs always quotes the value with spaces in it, so the actual command it executes becomes this:

```
asdf global 'rust 1.67.0'
```

and of course does not work with asdf as it expects to arguments to `asdf global`, not one.

Instead you need to bang your head on the keyboard for a while to find a simple cross-platform solution and eventually you'll end up with pure awk because it can execute system commands:

```
awk -F'\n' '{ system("asdf global " $0) }' < .tool-versions
```

So if you're not good at hacking solutions together with ancient Unix tools you're going to have a bad time. But all of this could be avoided if asdf would just implement features that the users ask for so we do not need to waste hours of our lives hacking around deficiencies due to a project maintainer rejecting simple requests from its users who know what their problems are and why they need these solutions.
