### ISSUE TITLE
Bug in add asdf in zsh

### ISSUE THREAD

**Issue by felipecaninnovaes** [asdf-vm/asdf#716]
**Is your feature request related to a problem? Please describe.**
the subsequent update on the method of adding asdf to zsh, both on fedora 32 and arch, on the official website stopped working, 

**Describe the solution you'd like**
return old code "echo -e "\n. $HOME/.asdf/asdf.sh" >> ~/.zshrc".

**System**
Fedora 32 KDE and Arch Linux

_thanks_

**Comment by jthegedus** [comment]
Hi @felipecaninnovaes 

Since everyone's shell and `.*rc` files are different and highly custom, we decided to move away from running a command which appends to the end of the config file. Instead, we now just instruct which lines need to be added to the file. It is up to you to decided **where** within that file it goes.

**Comment by felipecaninnovaes** [comment]
OK thank you for the attention
