### ISSUE TITLE
[Proposal] Compiled binaries

### ISSUE THREAD

**Issue by HashNuke** [asdf-vm/asdf#73]
Some tools take up a lot of compile time (15-20min for Erlang I've noticed). Not ideal for CI and tiny machines. Can we have pre-built binaries for certain operating systems?

We could start with one language for Mac & Ubuntu. Then fan out to do Erlang.

Assuming we can find a sponsor for hosting over time...

**Comment by tuvistavie** [comment]
This is definitely something I would like, compiling Erlang or Ruby needs quite a lot of resources.

Where would you suggest hosting the binaries to start with?

**Comment by duijf** [comment]
[Bintray](https://bintray.com/) offers free hosting for open source projects. I think Homebrew caches binaries on their servers (their URLs used to show up in installation logs).

(Not affiliated in any way, just thought it'd be helpful to mention)

**Comment by tuvistavie** [comment]
@duijf Thanks for idea! Bintray indeed seems a very nice choice for this, and if it is free for open-source, it's perfect.
@HashNuke What do you think?

**Comment by tisba** [comment]
Compiling Ruby is relatively fast, compared to building Erlang from source. Is hosting the binaries still the main concern for this?

**Comment by vic** [comment]
Dont know if linked libraries could also be an issue, for example if I have some dll on one location and ruby was built with them on another or with another version. Also I guess we could have bins only for osx and ubuntu and other most commonly used linuxes.

**Comment by vic** [comment]
Hey, just adding to this thread, I've built a tiny repo [asdf-alpine](https://github.com/vic/asdf-alpine) to provide docker images of some asdf toolsets (an image can contain more than one asdf tool installed, as is the case of elixir), checkout the readme if you are interested. I made it mainly for creating asdf-installed elixir containters for development and production (that's why I started with alpine linux). Hope someone finds it useful or wishes to add a new image to it.

**Comment by Stratus3D** [comment]
I think we should close this. Some plugins can already used pre-compiled binaries for certain systems (asdf-elixir, and maybe asdf-ruby?). Even Erlang has pre-compiled packages available from Erlang solutions. I think this should be left up to the plugin maintainers and the communities around the individual programming languages. Some have pre-compiled packages, and some do not. If they don't it's probably because there isn't enough man power in the community to make it worth while, in which case doing it ourselves would be a lot of work and wouldn't provide much benefit.

**Comment by Stratus3D** [comment]
I'm going to close this. We should support communities that want to offer pre-compiled binaries for certain version/operating system combinations by making it easy to build plugins that can both use pre-compiled packages and compile source code. But I think for the most part this is should left up to the language creators and the immediate community around the language.
