### ISSUE TITLE
Allow plugins to define if a file on bin should be linked instead of wrapped

### ISSUE THREAD

**Issue by arroadie** [asdf-vm/asdf#764]
**Is your feature request related to a problem? Please describe.**

when sbt is installed, it sets the executable `sbt-launcher.jar` on the shims folder with the following code

```shell
#!/usr/bin/env bash
# asdf-plugin: sbt 1.3.9
# asdf-plugin: sbt 1.3.13
exec [ASDF_PATH]/bin/asdf exec "sbt-launch.jar" "$@"
```

That way, when the sbt-launch is called from java, it fails to be used properly

```shell
$ java -jar [PATH_TO]/sbt-launch.jar
Error: Invalid or corrupt jarfile /Users/tferreiracosta/.asdf/shims/sbt-launch.jar
```

**Describe the solution you'd like**

Allowing plugins to define if files should be directly linked to the source instead of wrapping the executable with the shell code will make it so files like that can be referenced and the reshim process can switch between files the same way it does now with the version check.

**Describe similar asdf features and why they are not sufficient**

Run different versions of sbt using the shim as a path will break since the script isn't called directly

**Describe workarounds you've considered**

point to the actual install path

**Additional context**

none

**Comment by jthegedus** [comment]
This is an interesting proposal. However most people who want this functionality get it through https://github.com/asdf-community/asdf-direnv

There are many more issues to resolve in the asdf core before we would prioritize support for direct linking over shims, let alone a per-plugin hybrid approach.

Due to an existing solution and the lack of priority I will close this. We can revisit this idea in future. Thanks :pray:
