### ISSUE TITLE
Community chat, where to get help

### ISSUE THREAD

**Issue by morenoh149** [asdf-vm/asdf#766]
**Is your feature request related to a problem? Please describe.**
There should be clear instructions for where to go to get help. Stackoverflow tag, irc channel, gitter, something.

**Describe the solution you'd like**
I think a community irc channel on freenode or discord server would be great.

This type of stuff should be listed in the readme.

**Comment by jthegedus** [comment]
@morenoh149 I thought GitHub Issues was implied when looking for help.

>This type of stuff should be listed in the readme.

To right. I will add this to the README.

Currently the channel for communicating with the @asdf-vm/core is via GitHub Issues.

Community driven chat does not exist at this time. IMO I would like to keep as much communication, community or otherwise, within GitHub as it is then easily indexed by search engines and avoids rehashing previously solved/answered problems/questions.

GitHub have a [Discussions feature](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) which would be ideal (it's unclear if it's still in beta or off by default).

In the meantime I guess GitHub Issues. I hesitate to recommend or start a non-GitHub IRC at this time.

**Comment by Stratus3D** [comment]
I like the idea of documenting a Stackoverflow tag. Doing so will make it easier for people to ask for help there (or help answer questions!). https://stackoverflow.com/questions/tagged/asdf-vm is the tag I am watching.

**Comment by Stratus3D** [comment]
> Currently the channel for communicating with the @asdf-vm/core is via GitHub Issues.

I think this is probably best for the core team. If you need general help it's probably best to read the docs or ask on Stackoverflow or another community site and not bother the core team. If you've found a bug or have a feature request, then involve the core team by opening a GitHub issue of the appropriate type. I personally don't have the time to dedicate to StackOverflow or another communication method right now, and I suspect this is true for most of us on the core team.

**Comment by jthegedus** [comment]
@Stratus3D Can you look in the repo GitHub settings to see if Discussions is available for us? I cannot see it in other Orgs I am in, but they're not public so unsure if that is the reason I cannot see an option to enable it.

I second SO as being the next best place to ask questions.

"Where to get help" will be added to the Docs.

**Comment by Stratus3D** [comment]
@jthegedus I poked around the settings for the repo and the org and didn't find anything other than one setting at the org level that was already on (see screenshot) 

<img width="783" alt="Screen Shot 2020-08-10 at 9 07 28 AM" src="https://user-images.githubusercontent.com/1520926/89785850-01c2cc00-dae9-11ea-84ea-567c0d2cc468.png">

**Comment by jthegedus** [comment]
I guess we just have to wait for this to be released. A shame we cannot opt-in to the Beta

**Comment by jthegedus** [comment]
@morenoh149 You should now see GitHub Issues and StackOverflow links in the README and website Sidebar under a "Community and Questions" heading. While we don't have a traditional realtime chat-based community yet, we're awaiting GitHub Discussions as our preferred method over tools like Discord/Gitter etc.

**Comment by jthegedus** [comment]
GitHub Discussions is now live on this repo :tada: - https://github.com/asdf-vm/asdf/discussions

**Comment by makkes** [comment]
@jthegedus @Stratus3D the README [mentions discussions](https://github.com/asdf-vm/asdf#community--questions) as the preferred method for community Q&A and interaction but it looks like discussions have been turned off again. Is that a bug in the README or should discussion be revived here?
