### ISSUE TITLE
What's asdf-vm meaning?

### ISSUE THREAD

**Issue by lihsai0** [asdf-vm/asdf#796]
I apologize if bother you.

The name `asdf-vm` make me confused.

Is it a abbreviation?

**Comment by Stratus3D** [comment]
The name is actually just "asdf". I believe Akash chose asdf-vm for the org name was just for additional clarification of what asdf is - a Version Manager (vm). The name "asdf" doesn't have any meaning behind it. I believe it was simply chosen because of the arrangement of the home row keys on the keyboard.

**Comment by jthegedus** [comment]
asdf - (left-hand home row)
vm - Version Manager

It is also likely that the GitHub name for `asdf` was already taken.

We could communicate vm = Version Manager better on the website and README

**Comment by lihsai0** [comment]
@Stratus3D @jthegedus Thank you for answer!
