### ISSUE TITLE
Option to force compilation / ignore binary downloads.

### ISSUE THREAD

**Issue by toothbrush** [asdf-vm/asdf#811]
I'd be keen to have a way to tell `asdf` that regardless of what prebuilt binaries it finds, i want it to always do a compilation from source.  In my case, i'm running NixOS (Linux), and wanting to install NodeJS, which has precompiled binaries, but for boring reasons they do not work on NixOS.

I've managed to solve my problem with a workaround: in `.tool-versions` request a version like `nodejs ref:v12.18.3`, but it feels like a separate flag for this would be nice.

**Comment by jthegedus** [comment]
The download and installation of each tool is handled by the plugins which we provide this information to via the env var `ASDF_INSTALL_TYPE` (which is either `version` or `ref`).

The way I understand it, the core isn't aware if the binaries it shims were downloaded or compiled from source, so ultimately I believe the responsibility of this lies with each plugin maintainer.

It is on my radar to improve the guides for Plugin creation as I'm not sure many plugin authors are aware of this Env Var or how it would be helpful. We also recently added some new APIs for plugins to communicate their own documentation through the `asdf` command, so we can use that to drive plugin authors to communicate their support for source compilation or not. Lastly, we should also update `asdf help` to indicate installing via `ref`s and how some plugins use that to support compiling from source.

Ultimately, I am not sure another configuration option in the core would be useful for this since it is entirely dependent on the plugins.

Relevant docs: https://asdf-vm.com/#/core-configuration

PS: we also support `path:/src/nodejs` for custom compiled versions of tools.

**Comment by toothbrush** [comment]
Ah, that all sounds fair enough.  Indeed i found the workaround using `ref:...`.  This can probably be closed then :smiley_cat: Thanks for clarifying that!

**Comment by jthegedus** [comment]
To clarify for people who find this in future:

- Installing from source is performed by the plugin if it is supported at all.
- To install from a `ref` - `asdf install <tool> ref <version>`
- Use `ref` in `.tool-versions` - `<tool> ref:<version>`

**Comment by jthegedus** [comment]
I don't think so as it is still plugin specific, and most plugins will document how to utilise build from source as they require specific build deps, shell flags etc. I see this as a feature a small % of users actually use and the plugin is responsible for implementation and documentation, so the plugin is where most users will look for this.

**Comment by TechnologyClassroom** [comment]
After trying it with a few plugins, I see that this behavior is not consistent across plugins.

**Comment by jthegedus** [comment]
> After trying it with a few plugins, I see that this behavior is not consistent across plugins.

Yes, this is expected. Each plugin will have different requirements for how to perform a build from source. It is up to the plugin author whether they bother to add support to build from source or not. Some tools it doesn't make sense to build from source as they may be implemented in scripting langs etc. There is no universal solution to this issue, but the core of `asdf` exposes a way for plugins to support this and it is ultimately the plugin that would need to implement this.
