### ISSUE TITLE
Document ASDF_DIR variable

### ISSUE THREAD

**Issue by pikeas** [asdf-vm/asdf#865]
asdf sets and exports `ASDF_DIR`, but it's not clear what the purpose of this variable is. Yes, it points to the asdf install directory, but why is that a global variable? Everything seems to work fine even when it's unset, and it would be nice to keep the shell environment tidy when possible.

If the variable is optional, please consider revising the profile script so that it's not set by default, and adding a doc note on when users may want to set it themselves.

If the variable is required, please document how it is used.

**Comment by cho-m** [comment]
The original reason is partially included in [CHANGELOG.md](https://github.com/asdf-vm/asdf/blob/master/CHANGELOG.md#030) with corresponding PR:

> * Export `ASDF_DIR` variable so the Zsh plugin can locate asdf if it's in a custom location (#156)

It looks like this is important to be set when pointing to a non-default location since ASDF's plugins can use it, like in [asdf-nodejs install command](https://github.com/asdf-vm/asdf-nodejs/blob/5a46614ec24177146541543d3ec6327e136ae80f/bin/install#L240-L242):
```bash
      if [ -z "${GNUPGHOME:-}" ] && [ -d "${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" ]; then
        export GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs"
      fi
```

There is some limited (possibly outdated) documentation saying users should set `ASDF_DIR` when using a non-default location in [core-configuration.md](https://github.com/asdf-vm/asdf/blob/master/docs/core-configuration.md#environment-variables). Right now, this doesn't seem to matter since `asdf.sh` and `asdf.fish` do the export, so just sourcing one of those sets the variable.

It is likely that anyone using the default location of `$HOME/.asdf` will be fine without `ASDF_DIR` set.

I'll let one of current ASDF maintainers comment further on environment variable behavior and documentation.

**Comment by Stratus3D** [comment]
@pikeas does this answer your question? https://github.com/asdf-vm/asdf/pull/855

**Comment by Stratus3D** [comment]
Closing because I believe the updated docs answer the original question in this issue. `ASDF_DIR` doesn't need to be set unless you want asdf to operate from a directory other than the default of `~/.asdf`.

**Comment by Stratus3D** [comment]
The same goes for `ASDF_DATA_DIR`. Typically you do not need to set this variable. The default value should be what you need. Only if you want to store asdf data at a location other than `~/.asdf` do you need to set it.
