### ISSUE TITLE
Disable .tool-versions tracking in cwd

### ISSUE THREAD

**Issue by artemeff** [asdf-vm/asdf#870]
I'm always frustrated when my coworkers use .tool-versions files in projects, but I don't need to. I want to use asdf just like homebrew and install what I need when I need.

It would be great if we have some option in `.asdfrc` file to disable .tool-versions tracking in cwd :)

**Comment by Stratus3D** [comment]
You can override versions specified in `.tool-versions` using `asdf shell <tool> <version>` to set environment variables for the current shell. Is there a scenario that `asdf shell` does not cover?

**Comment by artemeff** [comment]
@Stratus3D and do it every time I cd in project? I can't even use language-server because it depends on this file. Every time I start to work on a project — I do rm .tool-versions.

asdf is a great tool, but I want to use it as a versions management to have as many as I want, but not for versions changing :)

I think it's pretty small feature and I can try to implement it by myself, but before I want to get some thoughts from contributors, maybe it's unacceptable feature.

**Comment by Stratus3D** [comment]
@artemeff so if asdf isn't getting the version from the `.tool-versions` file, how would it resolve versions? With the way it is right now, if there is no `.tool-versions` file, asdf prints a "no version set" message.

> and do it every time I cd in project? I can't even use language-server because it depends on this file. Every time I start to work on a project — I do rm .tool-versions.

What approach would not require running a command every time you enter the project? If there was no `.tool-versions` file you'd need to run `asdf local <tool> <version>` every time.

**Comment by artemeff** [comment]
@Stratus3D I have system-wide ~/.tool-versions file and that's all what I need :) Just install specific version and use it globally ignoring per project .tool-versions

**Comment by Stratus3D** [comment]
@artemeff I think I might have an approach that may work for you with the existing features:

asdf supports several env variables that can be used to alter its behavior (https://github.com/asdf-vm/asdf/blob/master/docs/core-configuration.md#environment-variables). One is `ASDF_DEFAULT_TOOL_VERSIONS_FILENAME`. Since nearly everyone uses `.tool-versions` you could do:

```
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.global-tool-versions
```

Now you don't have to delete `.tool-versions` files because asdf will automatically ignore them and look for `.global-tool-versions` instead. Then just rename your `~/.tool-versions` file to `~/.global-tool-versions` and you should have those versions available in project directories that specify other versions.

**Comment by Stratus3D** [comment]
Closing because I think the solution I proposed is sufficient and haven't heard back.

**Comment by artemeff** [comment]
@Stratus3D yea, thank you ❤️
