### ISSUE TITLE
Allow setting local/global versions of non-standard shim binaries

### ISSUE THREAD

**Issue by watzon** [asdf-vm/asdf#884]
**Is your feature request related to a problem? Please describe.**
Some languages, like Crystal, come packed with additional tools. In the case of Crystal you have `shards`, Crystal's package manager. The package manager versions don't necessarily coincide with the language version though. In my case I have a project that's currently on Crystal 0.35.1 which gets bundled with shards 0.11.1, but the dependencies in the project rely on shards 0.13.0.

**Describe the solution you'd like**
It would be nice if asdf was made aware of extra plugin binaries and their versions. Then in `.tool-version` I could say  that I want `crystal 0.35.1` and `shards 0.13.0` and have it shim both dependencies correctly.

**Describe similar asdf features and why they are not sufficient**
As far as I'm aware there isn't a way to do anything like this, other than having the extra binaries be installed as separate plugins.

**Describe workarounds you've considered**
Installing the version of shards I want globally and referencing it directly would probably work, but it's not ideal.

**Additional context**
n/a

**Comment by jthegedus** [comment]
This issue is not universal and the proposed solution is far too complex for the asdf core to be able to implement in any meaningful or even successful way.

This seems like an issue that could be addressed in the plugin itself. Plugins have access to many types of script callbacks during the execution of asdf commands, see our documentation for [creating a plugin](https://asdf-vm.com/plugins/create.html#environment-variables) for more.

I am closing this issue as it should almost certainly be addressed at the plugin level. Please raise there to discuss a solution with those authors.

**Comment by Stratus3D** [comment]
I agree with @jthegedus, this is too complicated for core but there are already two ways to solve this:

* Separate plugins for crystal and shards. In your `.tool-versions` specify the version for each one.
* Update the crystal plugin to also install shards alongside crystal (maybe make it an option so some folks can disable this if they don't want it).
