### ISSUE TITLE
Bug with nodejs, npm and angular

### ISSUE THREAD

**Issue by d3v0m4r** [asdf-vm/asdf#904]
Hi everyone
I install nodejs everything as the documentation says
but when installing angular cli with npm when wanting to use the ng command I get command not found: ng
if you could check it please
because with other tools like nvm something like this didn't happen
regards from Bolivia

**Comment by jthegedus** [comment]
Please try running `asdf reshim nodejs`.

Since it is not clear this is an issue with the core of `asdf` or the `asdf-nodejs` plugin I will close this hear. Please ask plugin specific questions on the plugin repo so it can be identified is this is an error in the plugin or the plugin usage before opening here.
