### ISSUE TITLE
Allow environment variables to be specified in tool-versions

### ISSUE THREAD

**Issue by iloveitaly** [asdf-vm/asdf#932]
Some projects require additional configuration options for packages to be specified. It would be great if these could be specified in the `tool-versions` file, allowing a simple `asdf install`, which would avoid additional installation instructions in a readme. 

**Describe the solution you'd like**

Ability to specify environment variables for specific installations within `tool-versions`. Something along the lines of:

```
export PYTHON_CONFIGURE_OPTS="--enable-framework"
python 3.7.10
```

**Comment by jthegedus** [comment]
After thinking about this for a few days, my thoughts are:

I don't like the proposal because it only applies to one use case of the `asdf install` command (that which reads the `.tool-versions` file and attempts to install each tool:version pair within). That specific use case of `asdf install` was added as a utility function to ease the singular specific case of bumping all tools at once in a single project.

This further clouds the usage of `asdf install` which is most commonly used without a `.tool-versions` file.

Will leave this open for further discussion.

**Comment by RobLoach** [comment]
You could possibly use something like this: https://github.com/excid3/asdf-vars

**Comment by iloveitaly** [comment]
Bummer that asdf-vars uses a separate file. https://direnv.net seems like a more mature approach and uses a separate file as well.

**Comment by RobLoach** [comment]
Didn't know of direnv! This is great, thanks.

**Comment by hyperupcall** [comment]
Would like to add my input and say that I'm not for this proposal either. Currently, `.tool-versions` is strictly declarative and this would make it much more imperative. Not to mention that there will be side effects that will need to be dealt with. I'm also building a tool that aims to have 100% compatibility with the existing `.tool-versions` file, so this would make it more difficult. Also direnv was mentioned, which already solves this perfectly - I myself maintain the popular [autoenv](https://github.com/hyperupcall/autoenv), and there are still some unanswered questions related to how and when to "unload" [environment ]variables. So all in all I think its better to delegate this responsibility to a different tool and not implement it yet again in another tool

**Comment by iloveitaly** [comment]
I'd agree here—I think direnv/asdf-vars approach makes more sense given the small scope of the responsibility the `.tool-versions` has.
