### ISSUE TITLE
Ability to specify a different default plugins repository

### ISSUE THREAD

**Issue by adongy** [asdf-vm/asdf#952]
**Is your feature request related to a problem? Please describe.**

Imagine a workplace where plugins should be internalized to assume full control before being usable. Users should only install these vetted plugins. Currently, users have to specify a custom plugin URL for each of these plugins.

**Describe the solution you'd like**
I'd like to be able to change the default repository URL for plugins, currently located in https://github.com/asdf-vm/asdf/blob/0a3865d0b1f8adad4f4d612869abd801e1c2a27d/lib/utils.bash#L35-L37

**Describe similar asdf features and why they are not sufficient**

The plugin list may list plugins that are actually not allowed.

**Additional context**

It could be a setting in the .asdfrc. 

Thanks,

**Comment by jthegedus** [comment]
>Currently, users have to specify a custom plugin URL for each of these plugins

This is preferred behaviour as it is explicit and users are informed that plugins are merely git repos and not magic of asdf.

I think this should be a setting. `.asdfrc` is the place to have it.

I would like to note that the plugin repo format is subject to change which would require updates to external plugin repos.

**Comment by adongy** [comment]
Yes I believe .asdfrc is a good place for it.

The repository URL could be printed alongside the current logs to ease debug and avoid people reporting issues when using a custom repository.

https://github.com/asdf-vm/asdf/blob/32371673384ae7ddba3532670d6c04b3f7dce249/lib/utils.bash#L393

As to the repo format, that would mean format update need to be documented so that plugin repository operators can update the format accordingly.

**Comment by jthegedus** [comment]
>The repository URL could be printed alongside the current logs to ease debug and avoid people reporting issues when using a custom repository

Yes, that is a good suggestion.

>As to the repo format, that would mean format update need to be documented so that plugin repository operators can update the format accordingly

Yes, we should document it when we get to a stable release. Adding this as a configurable option would mean we are essentially expanding an API scope. We are using semver and on version `0.x.x`, which means our feature-set and API are not yet set in stone.

**Comment by jthegedus** [comment]
After thinking about this more I don't think the idea of custom plugins repo is a good idea.

>Currently, users have to specify a custom plugin URL for each of these plugins

This is the preferred user flow. The plugin repo only saves users typing/copy-pasting the `<git-url>` portion of the command, so that isn't a valid reason IMO. If it's for discoverability, there are many other solutions to just sharing URLs amongst your project/team.

`asdf plugin add <name> <git-url>` is preffered because:
- it always works
- doesn't require syncing a remote plugin repo 
- doesn't require us to create a new API (via the concrete plugin repo spec)
- requires users know that plugins are just Git repos and not special `asdf` sauce
- makes users aware of the source of the plugin code (most plugins are not created or maintained by the `asdf` core team)

`asdf plugin add <name>` is good because:
- saves on typing?

If I have misunderstood the benefits of the short-name plugin repo, please share. Each day I sour more on the plugin repo.

**Comment by jthegedus** [comment]
I am closing this as `asdf plugin add <name>` achieves the same result.

We're going to explore plugin search of remote VCS (GitHub/GitLab/BitBucket) which would supplant this request as we could allow people to define the list of remotes for internal/private VCS platforms.

**Comment by Stratus3D** [comment]
Agree with @jthegedus. I understand how not having this feature make be an inconvenience but I think it isn't worth adding another feature to asdf to support this since the only thing it really does it allow the user to skip specifying the repo URL. I personally think `asdf plugin <name> <url>` is the only API we should provide.

I also don't think the plugin repository has been worth the contributor time that has been put into it. A simple GitHub or Google search for `asdf-<plugin name>` will usually turn up all public plugins with the name.
