### ISSUE TITLE
Check all julia versions installed

### ISSUE THREAD

**Issue by Flock1** [asdf-vm/asdf#977]
**Is your feature request related to a problem? Please describe.**

It is related to a problem. I want a list of all the julia versions installed

Maintaining different versions installed is really tricky and it gets frustrating. So there should be something to give a list of all the Julia versions installed

**Describe the solution you'd like**

A command that goes through the usual folders and sees what other Julia versions are installed and manages them. 

However we want to manage it, the commands you have should also apply to other Julia versions as well. 

**Describe similar asdf features and why they are not sufficient**

They only work on versions installed through `asdf`.

I am facing issues with setting Julia version for my work. Even after using `global` command, the Julia that I am forced to use is some other version. So maybe, `asdf` isn't able to change it. So this feature might be able to help with this issue.

**Comment by Stratus3D** [comment]
> It is related to a problem. I want a list of all the julia versions installed
> 
> Maintaining different versions installed is really tricky and it gets frustrating. So there should be something to give a list of all the Julia versions installed

If all you want is a list of the installed versions, use the `asdf list` command, like this: `asdf list julia`.

> A command that goes through the usual folders and sees what other Julia versions are installed and manages them.
>
> However we want to manage it, the commands you have should also apply to other Julia versions as well.

If you are wanting to find Julia versions that are installed but aren't "used" anywhere on your system see this previous issue  - https://github.com/asdf-vm/asdf/issues/819

> Describe similar asdf features and why they are not sufficient
>
> They only work on versions installed through asdf.

asdf only operates on asdf-installed versions. Managing versions installed by other means is not supported and never will be. Some plugins do offer ways of migrating versions installed via other methods into asdf, but this is relatively rare and is up to the maintainer's of the plugin.

I am closing this issue because I don't think there are any in-scope enhancements to be made here that haven't already been discussed on other threads.
